### ISSUE TITLE
Concourse login error

### ISSUE THREAD

**Issue by fpiedrah** [EugenMayer/concourseci-server-boilerplate#7]
Hi! I'm running the fly login command but I'm getting a weird error.

I'm running the default config, just ran docker-compose up and that's all.

**Command:** 
```
fly -t lite login -c http://127.0.0.1:8080 -u included1 -p included1
```

**Output:**
```
logging in to team 'main'

error: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_request","error_description":"Requested connector does not exist."}
``` 

**Expected Behavior:** I would expect to get a successful connection to vault by doing this.

Tanks for the help!

**Comment by EugenMayer** [comment]
Not sure this i working anymore, you need to do it this way

https://github.com/EugenMayer/concourseci-server-boilerplate#configuration

`fly -t lite login -c http://127.0.0.1:8080` and then login using ur browser. What u try is not possible since i think 4.2.1 or similar

**Comment by russmack** [comment]
> not possible since i think 4.2.1

The options are still available.
